name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - JTF4
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: distro
    attributes:
      label: Distribution
      description: What distribution of TallyArbiter are you running?
      options:
        - Desktop
        - CLI
        - Docker
        - Source
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating system are you running?
      options:
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: clients
    attributes:
      label: If applicable, What Listener Clients are You Using?
      multiple: true
      options:
        - Web (Chrome)
        - Web (Safari)
        - Web (Firefox)
        - Web (Microsoft Edge)
        - M5 Stick
        - Blink(1)
        - Blinkt
        - Relay
        - GPI
  - type: textarea
    id: config
    attributes:
      label: TallyArbiter configuration
      description: Please copy and paste here your config.json file. This will be automatically formatted into code, so no need for backticks.
      render: javascript
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: stacktrace
    attributes:
      label: Error stacktrace (if applicable)
      description: Please copy and paste the error stacktrace, if you have it. This will be automatically formatted into code, so no need for backticks.
      render: shell
